import { buildNameIndex, resolveLinkTarget, isContent } from './graph.mjs';

// Pages that exist to point at other pages. index.md catalogs everything and a
// MOC's whole job is linking, so an inbound edge from one carries no evidence
// that the target belongs to a topic. They are excluded from the "is anything
// outside the set referencing this?" test — never from being purged, which a
// seed can still do explicitly.
// Mirrors graph.mjs's SYSTEM_FILES (graph.mjs:11) for the file-set part; if a
// fourth system file is ever added there, add it here too.
const STRUCTURAL_FILES = new Set(['index.md', 'log.md', 'vault-schema.md']);
// Deliberately NOT the same prefix set graph.mjs's isContent() excludes:
// raw/ is omitted because clippings are purge targets, not structure, and
// wiki/syntheses/ is omitted because — unlike graph.mjs's isRoot(), which
// groups syntheses with moc/ as link-hub roots — purge must treat a synthesis
// as ordinary content that can be the off-topic survivor of a closure.
const STRUCTURAL_PREFIXES = ['moc/', 'log/', '_templates/'];

export function isStructural(path) {
  return STRUCTURAL_FILES.has(path) || STRUCTURAL_PREFIXES.some((p) => path.startsWith(p));
}

// Inverts the graph: target path -> set of page paths linking to it. The two
// link channels resolve differently and mixing them up silently mis-attributes
// provenance edges — body wikilinks ask the navigation question (nav: true),
// `sources:` frontmatter asks the provenance question (nav: false). Same
// convention as graph.mjs's computeGraphMetrics().
export function inboundMap(pages, byName) {
  const inbound = new Map(pages.map((p) => [p.path, new Set()]));
  const add = (from, target, nav) => {
    const to = resolveLinkTarget(byName, target, { nav });
    if (to && to !== from && inbound.has(to)) inbound.get(to).add(from);
  };
  for (const p of pages) {
    for (const t of p.outTargets ?? []) add(p.path, t, true);
    for (const t of p.fmTargets ?? []) add(p.path, t, false);
  }
  return inbound;
}

// Grows a purge set from explicit seeds by repeatedly admitting any page whose
// every non-structural referent is already inside. Deliberately asymmetric:
// over-matching destroys work and is discovered late, under-matching leaves one
// page to delete by hand and is discovered immediately. So a page with ANY
// outside referent is never admitted — it becomes collateral instead.
//
// Returns { purge, collateral, blocking }, all sorted vault-relative paths.
//   purge      — move these
//   collateral — survive, but link into the set; their references need repair
//   blocking   — survive, but ALL their provenance is inside the set. Guardrail
//                #2 says a claim with no evidence is a defect, so purge stops
//                and asks rather than guessing.
export function planPurge({ pages, seedPaths }) {
  const byName = buildNameIndex(pages);
  const inbound = inboundMap(pages, byName);
  const known = new Set(pages.map((p) => p.path));
  const set = new Set(seedPaths.filter((p) => known.has(p)));

  let grew = true;
  while (grew) {
    grew = false;
    for (const p of pages) {
      if (set.has(p.path) || isStructural(p.path)) continue;
      const refs = [...inbound.get(p.path)].filter((r) => !isStructural(r));
      // No referent at all is not evidence of topic membership — an orphan
      // unrelated to the topic would otherwise be swept in by vacuous truth.
      if (refs.length === 0) continue;
      if (refs.every((r) => set.has(r))) {
        set.add(p.path);
        grew = true;
      }
    }
  }

  const targetsOf = (p) => [
    ...(p.outTargets ?? []).map((t) => resolveLinkTarget(byName, t, { nav: true })),
    ...(p.fmTargets ?? []).map((t) => resolveLinkTarget(byName, t)),
  ].filter(Boolean);

  // The collateral/blocking pool asks a DIFFERENT question from the refs filter
  // above ("does this page need reference repair?" vs "is this an outside
  // referent?"), so it uses a different predicate. isContent excludes index.md
  // (regenerated by index-gen.mjs, never repaired), log/ (an immutable audit
  // trail — you do not rewrite history), _templates/, and raw/ (guardrail #1:
  // raw bodies are immutable, so a dangling link there is never ours to fix).
  // It KEEPS moc/, which isStructural would have dropped — a MOC linking into
  // the purged set has real broken links, isContent('moc/x.md') is true so
  // health.mjs counts them, and nothing regenerates a MOC.
  const survivors = pages.filter((p) => !set.has(p.path) && isContent(p.path));

  const collateral = survivors
    .filter((p) => targetsOf(p).some((t) => set.has(t)))
    .map((p) => p.path)
    .sort();

  const blocking = survivors
    .filter((p) => {
      const evidence = (p.fmTargets ?? []).map((t) => resolveLinkTarget(byName, t)).filter(Boolean);
      return evidence.length > 0 && evidence.every((e) => set.has(e));
    })
    .map((p) => p.path)
    .sort();

  return { purge: [...set].sort(), collateral, blocking };
}
